version: '3'
services:
  postgres:
    image: postgres:11.2
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
    volumes:
      - ./database/install.sql:/docker-entrypoint-initdb.d/db.sql
      - .volumes/postgresql:/var/lib/postgresql/data
    networks:
      - default

  mockserver:
    build:
      context: mock-server/
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    networks:
      - default

  idb:
    build:
      context: IDBService/
      dockerfile: ./Dockerfile
    ports:
      - "9000:9000"
    environment:
      - ETHEREUM_NODE_URL=http://34.74.56.215:4545
    networks:
      - default

  cross-boarder:
    build:
      context: crossboarder-app/
      dockerfile: ./docker/Dockerfile
    ports:
      - 9092:9092
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - CITI_PROXY_HOST=mockserver
      - CITI_PROXY_PORT=8080
      - BACK_BLOCKCHAIN_HOST=idb
      - BACK_BLOCKCHAIN_PORT=9000
      - RESET_PASSWORD_URL=http://localhost:3000/reset-password
      - SMTP_PASSWORD=Password
    depends_on:
    - postgres
    - mockserver
    - idb
    networks:
      - default

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - $HOME/mongodb/data/db:/data/db
    networks:
      - default

  eventeum:
    image: eventeum/eventeum:latest
    ports:
    - "8060:8060"
    depends_on:
      - cross-boarder
      - mongodb
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      ETHEREUM_NODE_URL: http://34.74.56.215:4545
      BROADCASTER_TYPE: HTTP
      BROADCASTER_HTTP_CONTRACTEVENTSURL: http://cross-boarder:9092/crossborder/api/event
      BROADCASTER_HTTP_BLOCKEVENTSURL: http://cross-boarder:9092/crossborder/api/block
      BROADCASTER_EVENT_CONFIRMATION_NUMBLOCKSTOWAIT: 1
    networks:
      - default

  curl:
    build:
      context: crossboarder-app/
      dockerfile: ./docker/curl/Dockerfile
    depends_on:
      - eventeum
    networks:
      - default